### ISSUE TITLE
Clarify functionality coverage relative to GSW-C

### ISSUE THREAD

**Issue by efiring** [castelao/GSW-rs#61]
I think that the readme and the joss paper need to say something about the subset of GSW that is already implemented, and perhaps about how much that subset might (or won't) be expanded.  In particular, comparison to the current state of the C implementation would be useful.  It should be made clear that using the current Rust implementation as a plugin replacement for the C library in the Python implementation will result in considerably reduced functionality.  I haven't looked closely enough to figure out how this is handled in your CI when you do plug in the Rust and then run the Python tests.

**Comment by castelao** [comment]
That's a good point. The goal is to eventually cover everything that GSW-C provides, but we should have it clear what is missing instead of having it implicit by what is not in our documentation. I'll work on that. Thanks,

**Comment by efiring** [comment]
All good, thank you.
