### ISSUE TITLE
README could contain more information about the project

### ISSUE THREAD

**Issue by wentasah** [castelao/GSW-rs#63]
Why rewrite in rust? What are the benefits compared to the C implementation? If you are faster, mention that and write how much. If you are “safer”, mention why it matters.

I see that this is answered in `doc/talks`, but this document is not easily accessible (one has to download the repo and open the file locally). It would be great if the main goals are mentioned directly in the top-level `README.md`.

**Comment by castelao** [comment]
Good point. I'll work on that. Thanks!

**Comment by castelao** [comment]
A reminder for myself - Add a statement of need in the documentation. I have no opinion yet if explicit or implicit.

**Comment by castelao** [comment]
@wentasah , thanks again for raising this issue. Does #68 covers everything? You might also enjoy this [benchmark](https://gsw.castelao.net/dev/bench/).

**Comment by wentasah** [comment]
Yes, this looks file. Thank you.

**Comment by castelao** [comment]
Thank you!
